stages:
  preprocess:
    cmd: python -m src.preprocessing
    deps:
      - src/preprocessing.py
      - config/paths.py
      - config/settings.yaml
      - data/raw
    outs:
      - data/processed/processed_data.parquet
      - artifacts/valid_users.pkl
      - artifacts/valid_movies.pkl

  train:
    cmd: python -m src.train
    deps:
      - src/train.py
      - src/model.py
      - config/paths.py
      - config/settings.yaml
      - data/processed/processed_data.parquet
    outs:
      - models/svd_model.pkl
      - outputs/test_set.parquet

  evaluate:
    cmd: python -m src.evaluate
    deps:
      - src/evaluate.py
      - src/model.py
      - config/paths.py
      - config/settings.yaml
      - models/svd_model.pkl
      - outputs/test_set.parquet
    metrics:
      - outputs/metrics.json:
          cache: false

  recommend:
    cmd: python -m src.recommend
    deps:
      - src/recommend.py
      - src/model.py
      - config/paths.py
      - config/settings.yaml
      - models/svd_model.pkl
      - data/processed/processed_data.parquet
      - data/raw/qualifying.txt
      - data/raw/movie_titles.csv
    outs:
      - outputs/recommendations.parquet
